CREATE SCHEMA IF NOT EXISTS "$SchemaName$";

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricDef" (
    "MetricDefId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(128) NOT NULL UNIQUE,
    "Unit" varchar(32) NOT NULL,
    "AggKind" varchar(16) NOT NULL,
    "Description" varchar(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricSeries" (
    "SeriesId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MetricDefId" integer NOT NULL REFERENCES "$SchemaName$"."MetricDef" ("MetricDefId"),
    "DatabaseId" uuid NOT NULL,
    "Service" varchar(64) NOT NULL,
    "TagsJson" varchar(1024) NOT NULL DEFAULT '{}',
    "TagHash" bytea NOT NULL,
    "CreatedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UQ_MetricSeries" UNIQUE ("MetricDefId", "DatabaseId", "Service", "TagHash")
);

CREATE TABLE IF NOT EXISTS "$SchemaName$"."MetricPointHourly" (
    "SeriesId" bigint NOT NULL REFERENCES "$SchemaName$"."MetricSeries" ("SeriesId"),
    "BucketStartUtc" timestamptz NOT NULL,
    "BucketSecs" smallint NOT NULL,
    "ValueSum" double precision NULL,
    "ValueCount" integer NULL,
    "ValueMin" double precision NULL,
    "ValueMax" double precision NULL,
    "ValueLast" double precision NULL,
    "P50" double precision NULL,
    "P95" double precision NULL,
    "P99" double precision NULL,
    "InsertedUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_MetricPointHourly" PRIMARY KEY ("SeriesId", "BucketStartUtc", "BucketSecs")
);

CREATE INDEX IF NOT EXISTS "IX_MetricPointHourly_ByTime"
    ON "$SchemaName$"."MetricPointHourly" ("BucketStartUtc");

CREATE TABLE IF NOT EXISTS "$SchemaName$"."ExporterHeartbeat" (
    "InstanceId" varchar(100) NOT NULL,
    "LastFlushUtc" timestamptz NOT NULL,
    "LastError" varchar(512) NULL,
    CONSTRAINT "PK_ExporterHeartbeat" PRIMARY KEY ("InstanceId")
);
